<div class="wrapper wrapper--twitter">
	<div class="wrapper--twitter_restrict flow">
		<h2>Pledges So Far</h2>
		<?php
			// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
			$ch = curl_init();
			
			curl_setopt($ch, CURLOPT_URL, 'https://api.buttondown.email/v1/subscribers');
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
			
			
			$headers = array();
			$headers[] = 'Authorization: Token a501317c-9cf7-4fb2-bd84-b76d66a31010';
			curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
			
			$result = curl_exec($ch);
			if (curl_errno($ch)) {
			    echo 'Error:' . curl_error($ch);
			}
			curl_close($ch);
			print_r($result['count']);
			?>
	</div>
</div>